name: Build PrintSpoofer
 
on: [push]
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses:  warrenbuckley/Setup-MSBuild@v1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore PrintSpoofer.sln
 
    - name: Build and Publish Web App
      run: msbuild PrintSpoofer.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile /p:OutputPath=D:\a\newbuild\
 
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: PrintSpoofer
        path: "D:/a/newbuild/"
